sudo: required

before_install:
  - gem install package_cloud

script:
  - bash build.sh
  - package_cloud push nitrux/repo/debian/trixie files/*.deb

branches:
  except:
    - "/^(?i:continuous.*)$/"

notifications:
  email: false
